name: Build CyberUI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./  # change this to your mod folder if not root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Build mod
      run: |
        # Check if gradlew exists
        if [ -f ./gradlew ]; then
          echo "Using Gradle wrapper"
          chmod +x ./gradlew
          ./gradlew build
        else
          echo "Gradle wrapper not found, installing Gradle"
          sudo apt-get update
          sudo apt-get install -y gradle
          gradle build
        fi

    - name: Upload compiled jar
      uses: actions/upload-artifact@v4
      with:
        name: CyberUI-jar
        path: build/libs/*.jar
